# Generated by Django 5.2.13 on 2026-04-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_jobexecution_cancel_requested_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexecution',
            name='job',
        ),
        migrations.DeleteModel(
            name='SchedulerRuntime',
        ),
        migrations.DeleteModel(
            name='SchedulerSettings',
        ),
        migrations.DeleteModel(
            name='JobExecution',
        ),
        migrations.DeleteModel(
            name='ScheduledJob',
        ),
    ]
