# Generated by Django 5.2.13 on 2026-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_blockverificationrun_blockverificationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockprocessing',
            name='totvs_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blockverificationitem',
            name='totvs_status_banco_antes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blockverificationitem',
            name='totvs_status_banco_depois',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blockverificationitem',
            name='totvs_status_real',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
