# Generated by Django 5.2.13 on 2026-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotvsIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TOTVS principal', max_length=120)),
                ('base_url', models.URLField(default='https://fmimpressos170648.protheus.cloudtotvs.com.br:2007', help_text='Informe apenas a base do ambiente. Ex.: https://host:porta')),
                ('tenant_id', models.CharField(default='01,01', max_length=40)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Auth')], default='basic', max_length=20)),
                ('credential_key', models.CharField(blank=True, help_text='Referencia interna da credencial guardada no cofre do sistema.', max_length=120, unique=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao TOTVS',
                'verbose_name_plural': 'Configuracoes TOTVS',
                'db_table': 'totvs_integration_configs',
                'ordering': ['-active', 'name'],
            },
        ),
    ]
